apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
# Flagger의 Canary 리소스 추가
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: reviews
  namespace: default
spec:
  # 감시 및 배포 대상 설정
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reviews-v1 # Flagger가 감시할 원본 배포판 (해당 이미지 변경시 배포 시작)
  # Flagger가 자동으로 생성할 서비스/게이트웨이 설정
  service:
    port: 9080
    gateways:
    - bookinfo-gateway
    hosts:
    - "*"
    trafficPolicy: # 서비스 메쉬 내 보안 설정
      tls:
        mode: ISTIO_MUTUAL # mTLS
  # 배포 및 롤백 전략 (기술적 근거)
  # analysis:
  #   interval: 1m # 30초마다 Prometheus 지표 체크
  #   threshold: 10 # 실패 임계치
  #   maxWeight: 50 # 신규 버전으로 보내는 트래픽을 최대 50%까지 확장
  #   stepWeight: 10 # 한 번의 분석 주기마다 트래픽을 10%씩 점진적으로 올림
  #   metrics:
  #     - name: request-success-rate # HTTP 요청 성공률
  #       thresholdRange:
  #         min: 95 # 성공률 99% 미만의 경우 실패로 간주
  #       interval: 1m # 최근 1분간 데이터 합산하여 계산
  analysis:
    interval: 30s
    threshold: 5
    iterations: 10
    match:
      - headers:
          user-agent:
            regex: ".*Chrome.*"
      - headers:
          x-canary-test:
            exact: "true"      # 커스텀 헤더가 있는 요청만 타겟팅
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 95
        interval: 1m